import type { Metadata } from 'next';
import { Container } from '@/components/ui/Container';
import { buildMetadata } from '@/lib/metadata';
import { JournalSearch } from './JournalSearch';

/**
 * A query surface, not a document.
 *
 * `noindex, follow` because a search results page is generated by whatever the
 * visitor typed: indexing it would put an unbounded set of thin, near-duplicate
 * URLs into the index. `follow` keeps the links out of it useful.
 */
export const metadata: Metadata = buildMetadata({
  title: 'Search',
  description: 'Search publications in AgricultureID Journal.',
  path: 'search',
  noindex: true,
});

export default function SearchPage() {
  return (
    <Container className="py-8 lg:py-10">
      <h1 className="font-serif text-3xl text-forest-900">Search</h1>
      <div className="mt-6 max-w-3xl">
        <JournalSearch />
      </div>
    </Container>
  );
}
