import { journalUrl } from '@/lib/site';
import { escapeXml } from '@/lib/feed-items';
import {
  activeSections,
  promotedPublications,
  publicPublications,
} from '@/lib/publications';

export const dynamic = 'force-static';

/**
 * The Journal's own sitemap, at agricultureid.com/journal/sitemap.xml.
 *
 * It is generated by THIS project, so publishing an article updates it without
 * the main platform rebuilding. The main sitemap at /sitemap.xml is a separate
 * document owned by a separate deployment and is not touched here.
 *
 * Only publicly-routed items appear. A draft in a sitemap is an invitation to
 * index something nobody has approved.
 */
export async function GET() {
  const sections = await activeSections();
  const items = await publicPublications();
  const promoted = await promotedPublications();
  const newest =
    promoted[0]?.dateModified ?? promoted[0]?.datePublished ?? '1970-01-01';

  const urls: { loc: string; lastmod: string; priority: string }[] = [
    { loc: journalUrl(), lastmod: newest, priority: '1.0' },
    ...sections.map((s) => ({
      loc: journalUrl(s),
      lastmod:
        promoted.find((p) => p.section === s)?.dateModified ??
        promoted.find((p) => p.section === s)?.datePublished ??
        newest,
      priority: '0.7',
    })),
    ...items.map((p) => ({
      loc: journalUrl(`${p.section}/${p.slug}`),
      lastmod: p.dateModified ?? p.datePublished,
      priority: '0.8',
    })),
    ...['editorial-policy', 'sourcing-policy', 'corrections'].map((s) => ({
      loc: journalUrl(s),
      lastmod: newest,
      priority: '0.4',
    })),
  ];

  const body = `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urls
  .map(
    (u) => `  <url>
    <loc>${escapeXml(u.loc)}</loc>
    <lastmod>${u.lastmod}</lastmod>
    <priority>${u.priority}</priority>
  </url>`,
  )
  .join('\n')}
</urlset>
`;

  return new Response(body, {
    headers: { 'Content-Type': 'application/xml; charset=utf-8' },
  });
}
