/**
 * Prebuild step.
 *
 * The feeds, the sitemap and the two JSON contracts are all generated by route
 * handlers at build time, so there is nothing to precompute here yet. This
 * script exists as the hook for anything that must run before `next build` —
 * and, today, to make the editorial validation a hard prerequisite of the
 * build rather than a step somebody can forget.
 */
console.log(
  '  prebuild: editorial validation has already run; nothing to precompute.',
);
